copyright = "© Neco Entertainers"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/Los_Angeles"
timeout = "120s"
title = "Neco Entertainers"
[params]
  defaultTheme = "dark"
  description = "Models and masseuses"
  title = "Neco Entertainers"
  [params.author]
    email = "necoentertainers@gmail.com"
    name = "Email"
  [params.socialIcons]
    #instagram = ""
    #github = "https://github.com/necofilm"
    #youtube = ""
    email = "mailto:necoentertainers@gmail.com"
    website = "https://onlyfans.com/u402216658"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
    #whatsapp = ""
    flickr = "https://calendly.com/necoentertainers/"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[services]
  [services.rss]
    limit = 100

[services.googleAnalytics]
  id = 'G-VEYGTVRHVZ'
